// <auto-generated />
using System;
using Covauto.Domain;
using Covauto.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Covauto.Domain.Migrations
{
    [DbContext(typeof(LeenAutoContext))]
    [Migration("20250423095452_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Covauto.Domain.Entities.LeenAutoRit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KilometerstandBegin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KilometerstandEind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NaarAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VanAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VertrekTijd")
                        .HasColumnType("TEXT");

                    b.Property<int>("WerknemerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LeenAutoRitten");
                });
#pragma warning restore 612, 618
        }
    }
}
